on:
  schedule:
    - cron: '* 3 * * *'
jobs:
  syncfork:
    runs-on: ubuntu-latest
    steps:
      - uses: sakurayz/unlocker@main
        with:
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          upstream_repository: DrDonk/unlocker
          target_repository: sakurayz/unlocker
          upstream_branch: main
          target_branch: main
          force: true
          tags: true
